CREATE SEQUENCE SMER_ID_SEQ  MINVALUE 1 MAXVALUE 9999999999999999999 INCREMENT BY 1 START WITH 5 CACHE 20 ORDER  NOCYCLE ;
CREATE SEQUENCE OCENA_ID_SEQ  MINVALUE 1 MAXVALUE 9999999999999999999 INCREMENT BY 1 START WITH 54 CACHE 20 ORDER  NOCYCLE ;
CREATE SEQUENCE PREDMET_ID_SEQ  MINVALUE 1 MAXVALUE 9999999999999999999 INCREMENT BY 1 START WITH 404 CACHE 20 ORDER  NOCYCLE ;
CREATE SEQUENCE RODITELJI_ID_SEQ  MINVALUE 1 MAXVALUE 9999999999999999999 INCREMENT BY 1 START WITH 74 CACHE 20 ORDER  NOCYCLE ;
CREATE SEQUENCE ANGAZOVAN_NA_ID_SEQ  MINVALUE 1 MAXVALUE 9999999999999999999 INCREMENT BY 1 START WITH 115 CACHE 20 ORDER  NOCYCLE ;
CREATE SEQUENCE UCI_NA_ID_SEQ  MINVALUE 1 MAXVALUE 9999999999999999999 INCREMENT BY 1 START WITH 304 CACHE 20 ORDER  NOCYCLE ;
CREATE SEQUENCE IMA_CLANOVE_VECA_ID_SEQ  MINVALUE 1 MAXVALUE 9999999999999999999 INCREMENT BY 1 START WITH 18 CACHE 20 ORDER  NOCYCLE ;
CREATE SEQUENCE TELEFON_ID_SEQ  MINVALUE 1 MAXVALUE 9999999999999999999 INCREMENT BY 1 START WITH 95 CACHE 20 ORDER  NOCYCLE ;
CREATE SEQUENCE GODINE_ID_SEQ  MINVALUE 1 MAXVALUE 9999999999999999999 INCREMENT BY 1 START WITH 4 CACHE 20 ORDER  NOCYCLE ;
CREATE SEQUENCE UCENIK_ID_SEQ  MINVALUE 1 MAXVALUE 9999999999999999999 INCREMENT BY 1 START WITH 16 CACHE 20 ORDER  NOCYCLE ;

CREATE OR REPLACE TRIGGER "SMER_AUTO_PK" 
    BEFORE INSERT
    ON SMER
    REFERENCING NEW AS NEW
    FOR EACH ROW
BEGIN
    SELECT SMER_ID_SEQ.NEXTVAL INTO :NEW.ID_SMERA FROM DUAL;
END;

CREATE OR REPLACE TRIGGER "OCENA_AUTO_PK" 
    BEFORE INSERT
    ON OCENA
    REFERENCING NEW AS NEW
    FOR EACH ROW
BEGIN
    SELECT OCENA_ID_SEQ.NEXTVAL INTO :NEW.ID_OCENA FROM DUAL;
END;

CREATE OR REPLACE TRIGGER "PREDMET_AUTO_PK" 
    BEFORE INSERT
    ON PREDMET
    REFERENCING NEW AS NEW
    FOR EACH ROW
BEGIN
    SELECT PREDMET_ID_SEQ.NEXTVAL INTO :NEW.ID_PREDMETA FROM DUAL;
END;

CREATE OR REPLACE TRIGGER "RODITELJI_AUTO_PK" 
    BEFORE INSERT
    ON RODITELJI
    REFERENCING NEW AS NEW
    FOR EACH ROW
BEGIN
    SELECT RODITELJI_ID_SEQ.NEXTVAL INTO :NEW.ID_RODITELJA FROM DUAL;
END;

CREATE OR REPLACE TRIGGER "ANGAZOVAN_NA_AUTO_PK" 
    BEFORE INSERT
    ON ANGAZOVAN_NA
    REFERENCING NEW AS NEW
    FOR EACH ROW
BEGIN
    SELECT ANGAZOVAN_NA_ID_SEQ.NEXTVAL INTO :NEW.ID_ANGAZOVAN FROM DUAL;
END;

CREATE OR REPLACE TRIGGER "UCI_NA_AUTO_PK" 
    BEFORE INSERT
    ON UCI_NA
    REFERENCING NEW AS NEW
    FOR EACH ROW
BEGIN
    SELECT UCI_NA_ID_SEQ.NEXTVAL INTO :NEW.ID_UCI_NA FROM DUAL;
END;

CREATE OR REPLACE TRIGGER "IMA_CLANOVE_VECA_AUTO_PK" 
    BEFORE INSERT
    ON IMA_CLANOVE_VECA
    REFERENCING NEW AS NEW
    FOR EACH ROW
BEGIN
    SELECT IMA_CLANOVE_VECA_ID_SEQ.NEXTVAL INTO :NEW.ID_IMA_CLANOVE_VECA FROM DUAL;
END;

CREATE OR REPLACE TRIGGER "TELEFON_AUTO_PK" 
    BEFORE INSERT
    ON TELEFON
    REFERENCING NEW AS NEW
    FOR EACH ROW
BEGIN
    SELECT TELEFON_ID_SEQ.NEXTVAL INTO :NEW.ID_TELEFONA FROM DUAL;
END;
CREATE OR REPLACE TRIGGER "GODINE_AUTO_PK" 
    BEFORE INSERT
    ON GODINE
    REFERENCING NEW AS NEW
    FOR EACH ROW
BEGIN
    SELECT GODINE_ID_SEQ.NEXTVAL INTO :NEW.ID_GODINE FROM DUAL;
END;

CREATE OR REPLACE TRIGGER "UCENIK_AUTO_PK" 
    BEFORE INSERT
    ON UCENIK
    REFERENCING NEW AS NEW
    FOR EACH ROW
BEGIN
    SELECT UCENIK_ID_SEQ.NEXTVAL INTO :NEW.ID_UCENIKA FROM DUAL;
END;

ALTER TRIGGER "SMER_AUTO_PK" ENABLE;
ALTER TRIGGER "OCENA_AUTO_PK" ENABLE;
ALTER TRIGGER "PREDMET_AUTO_PK" ENABLE;
ALTER TRIGGER "RODITELJI_AUTO_PK" ENABLE;
ALTER TRIGGER "ANGAZOVAN_NA_AUTO_PK" ENABLE;
ALTER TRIGGER "UCI_NA_AUTO_PK" ENABLE;
ALTER TRIGGER "IMA_CLANOVE_VECA_AUTO_PK" ENABLE;
ALTER TRIGGER "TELEFON_AUTO_PK" ENABLE;
ALTER TRIGGER "GODINE_AUTO_PK" ENABLE;
ALTER TRIGGER "UCENIK_AUTO_PK" ENABLE;




